### ISSUE TITLE
NPE after deleting a role

### ISSUE THREAD

**Issue by bruestel** [gentics/mesh#1041]
## Gentics Mesh Version, operating system, or hardware.
- v1.4.0 and v1.4.3

## Operating System
- Linux using Docker-Compose

## Problem
NPE when indexing after deleting a role.

## Reproducer
1. create and remove role
2. start reindex

## Stacktrace
```
docker-compose[3564]: mesh-server      | Caused by: java.lang.NullPointerException: null
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.search.index.AbstractTransformer.addPermissionInfo(AbstractTransformer.java:123)
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.search.index.project.ProjectTransformer.toDocument(ProjectTransformer.java:34)
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.search.index.project.ProjectTransformer.toDocument(ProjectTransformer.java:17)
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.search.index.entry.AbstractIndexHandler.lambda$null$2(AbstractIndexHandler.java:222)
docker-compose[3564]: mesh-server      |         at com.gentics.madl.tx.TxFactory.lambda$tx$1(TxFactory.java:71)
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:399)
docker-compose[3564]: mesh-server      |         at com.gentics.madl.tx.TxFactory.tx(TxFactory.java:70)
docker-compose[3564]: mesh-server      |         at com.gentics.mesh.search.index.entry.AbstractIndexHandler.lambda$null$3(AbstractIndexHandler.java:222)
docker-compose[3564]: mesh-server      |         at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
docker-compose[3564]: mesh-server      |         ... 62 common frames omitted
```

**Comment by Jotschi** [comment]
Fixed within 1.4.9 LTS and 1.5.0
