### ISSUE TITLE
Vertx frontend question when using SSL(Https) 

### ISSUE THREAD

**Issue by digitalseas** [gentics/mesh#1045]
Hi,

I enabled SSL in the Mesh server, and Https://localhost:8443 is working fine with SSL. See the screenshot below.
![2020-04-07 10_56_10-Mesh UI](https://user-images.githubusercontent.com/8967340/78696696-6533b780-78c5-11ea-9f7a-a64b95994663.jpg)

The problem is when I try to use the Vertx frontend at https://localhost (from the gentics/mesh-vertx-example) to connect to the SSL-enabled Mesh server, there is an error for SSL handshake or the server just reject the connection. I tried to debug it but not sure what is missing because the error is vague. Please help! Thank you!

**When I use SSL Http://localhost:443 I am rejected by the Mesh Server: **
![2020-04-07 12_17_16-localhost](https://user-images.githubusercontent.com/8967340/78699626-d1181f00-78c9-11ea-857f-d5d712e6523a.jpg)

**When I use non-SSL Http://localhost:80 I have error: **

```Java
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
	at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl$2.onFailure(MeshOkHttpRequestImpl.java:115)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1974)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:345)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1098)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:343)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:226)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)
	... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 39 more
Exception in thread "OkHttp https://localhost:8443/..." io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
	at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl$2.onFailure(MeshOkHttpRequestImpl.java:115)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1974)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:345)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1098)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:343)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:226)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)
	... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 39 more
```

**The code that slightly modified from the vertex front example:**

```Java
package com.gentics.mesh.example;

import static io.vertx.core.http.HttpHeaders.CONTENT_TYPE;
import static io.vertx.core.http.impl.HttpUtils.normalizePath;
import static io.vertx.ext.web.handler.TemplateHandler.DEFAULT_CONTENT_TYPE;
import static io.vertx.ext.web.handler.TemplateHandler.DEFAULT_TEMPLATE_DIRECTORY;

import java.io.IOException;
import java.util.Optional;

import org.apache.commons.io.IOUtils;

import com.gentics.mesh.core.rest.graphql.GraphQLRequest;
import com.gentics.mesh.core.rest.graphql.GraphQLResponse;
import com.gentics.mesh.rest.client.MeshBinaryResponse;
import com.gentics.mesh.rest.client.MeshResponse;
import com.gentics.mesh.rest.client.MeshRestClient;
import com.gentics.mesh.rest.client.MeshRestClientConfig;
import com.gentics.mesh.rest.client.MeshWebrootResponse;
import com.google.common.net.HttpHeaders;

import io.reactivex.Single;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.json.JsonObject;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.templ.handlebars.HandlebarsTemplateEngine;

public class Server extends AbstractVerticle {

	static {
		// Enable if you want to edit the templates live
		// System.setProperty("io.vertx.ext.web.TemplateEngine.disableCache", "true");
	}

	private static final Logger log = LoggerFactory.getLogger(Server.class);

	private MeshRestClient client;

	private String topNavQuery;

	private String byPathQuery;

	private HandlebarsTemplateEngine engine;

	// Convenience method so you can run it in your IDE
	public static void main(String[] args) {
		VertxOptions options = new VertxOptions();
		Vertx vertx = Vertx.vertx(options);
		vertx.deployVerticle(new Server());
	}

	public void routeHandler(RoutingContext rc) {
		String path = rc.pathParam("param0");

		if (path.equals("favicon.ico")) {
			rc.response().setStatusCode(404).end("Not found");
			return;
		}

		// Render the welcome page for root page requests
		if (path.isEmpty()) {
			loadTopNav().subscribe(sub -> {
				rc.put("data", sub.getData());
				rc.put("tmplName", "welcome");
				rc.next();
			});
			return;
		}

		if (log.isDebugEnabled()) {
			log.debug("Handling request for path {" + path + "}");
		}

		if (path.endsWith(".jpg")) {
			handleImages(path, rc);
		} else {
			handlePage(path, rc);
		}
	}

	private void handlePage(String path, RoutingContext rc) {
		loadByPath(path, rc.request()).subscribe(sub -> {
			JsonObject data = sub.getData();
			// We render different templates for each schema type. Category
			// nodes show products and thus the productList template is
			// utilized for those nodes.
			JsonObject jo_node = data.getJsonObject("node");
			if (jo_node==null) {
				rc.response().setStatusCode(404).end("<html>404: Page not found. Please go back to the <a href='/'/>Front Page</a></html>");
				return;
			}
			JsonObject jo_schema = jo_node.getJsonObject("schema");
			String schemaName = jo_schema.getString("name");
			switch (schemaName) {
			case "category":
				rc.put("tmplName", "productList.hbs");
				rc.put("data", data);
				rc.response().putHeader(CONTENT_TYPE, "text/html");
				rc.next();
				break;
			// Show the productDetail page for nodes of type vehicle
			case "vehicle":
				rc.put("tmplName", "productDetail.hbs");
				rc.put("data", data);
				rc.response().putHeader(CONTENT_TYPE, "text/html");
				rc.next();
				break;
			}
		}, error -> {
			rc.fail(error);
		});

	}

	private String getQuery(String name) throws IOException {
		return IOUtils.toString(getClass().getResourceAsStream("/queries/" + name + ".graphql"));
	}

	private void handleImages(String path, RoutingContext rc) {
		// Resolve image path using the webroot API.
		resolvePath(path).subscribe(response -> {

			MeshWebrootResponse meshResponse = response.getBody();
			// The webroot API may have returned binary data for the specified path. We
			// pass the binary data along and return it to the client.
			if (meshResponse.isBinary()) {
				MeshBinaryResponse binaryResponse = meshResponse.getBinaryResponse();
				String contentType = binaryResponse.getContentType();
				HttpServerResponse serverResponse = rc.response();

				Optional<String> length = response.getHeader(HttpHeaders.CONTENT_LENGTH);

				if (length.isPresent()) {
					serverResponse.putHeader(HttpHeaders.CONTENT_LENGTH, length.get());
				} else {
					serverResponse.setChunked(true);
				}

				rc.response().putHeader(CONTENT_TYPE, contentType);
				binaryResponse.getFlowable()
					.map(Buffer::buffer)
					.subscribe(serverResponse::write, rc::fail, serverResponse::end);
				// Note that we are not calling rc.next() which
				// will prevent the execution of the template route handler.
				return;
			} else {
				// Return a 404 response for all other cases
				rc.response().setStatusCode(404).end("Not found");
			}
		}, rc::fail);
	}

	@Override
	public void start() throws Exception {
		// Connect to Gentics Mesh on https://demo.getmesh.io or http://localhost:8080
		log.info("Connecting to Gentics Mesh..");
		MeshRestClientConfig clientConfig = new MeshRestClientConfig.Builder()
		.setHost("localhost")
		.setPort(8443)
		.setSsl(true)
		//.setBasePath("/api/v2")
		.build();
		client = MeshRestClient.create(clientConfig);
		//client = MeshRestClient.create("localhost", 80, false);

		topNavQuery = getQuery("loadOnlyTopNav");
		byPathQuery = getQuery("loadByPath");
		engine = HandlebarsTemplateEngine.create(vertx);

		Router router = Router.router(vertx);
		router.routeWithRegex("/(.*)").handler(this::routeHandler).failureHandler(rc -> {
			log.error("Error handling request {" + rc.request().absoluteURI() + "}", rc.failure());
			rc.response().setStatusCode(500).end();
		});

		router.route().handler(rc -> {
			String page = rc.request().getParam("page");
			//System.out.println(page);
			rc.put("page", page);
			rc.next();
		});

		// Finally use the previously set context data to render the templates
		router.route().handler(this::templateHandler).failureHandler(rc -> {
			log.error("Error while rendering template {" + rc.get("tmplName") + "}", rc.failure());
			rc.response().setStatusCode(500).end();
		});

		int port = 80;
                //int port = 443;
		log.info("Server running on port " + port);
		vertx.createHttpServer().requestHandler(router).listen(port);
	}

	private void templateHandler(RoutingContext rc) {
		String file = rc.get("tmplName");
		engine.render(rc.data(), DEFAULT_TEMPLATE_DIRECTORY + "/" + normalizePath(file), res -> {
			if (res.succeeded()) {
				rc.response().putHeader(CONTENT_TYPE, DEFAULT_CONTENT_TYPE).end(res.result());
			} else {
				rc.fail(res.cause());
			}
		});
	}

	private Single<MeshResponse<MeshWebrootResponse>> resolvePath(String path) {
		// Load the node using the given path.
		return client.webroot("demo", "/" + path).getResponse();
	}

	private Single<GraphQLResponse> loadTopNav() {
		return client.graphql("demo", new GraphQLRequest().setQuery(topNavQuery)).toSingle();
	}

	private Single<GraphQLResponse> loadByPath(String path, HttpServerRequest request) {
		String query = byPathQuery;
		String pageParam = request.getParam("page");
		long page = 1;
		if (pageParam != null) {
			page = Integer.parseInt(pageParam);
		}
		//System.out.println(query);
		System.out.println(path);
		//System.out.println(page);
		return client.graphql("demo", new GraphQLRequest().setQuery(query).setVariables(new JsonObject().put("path", path).put("page", page)))
			.toSingle();
	}
}
```

**Comment by Jotschi** [comment]
It seems the MeshRestClient / OkHttp is rejecting the cert from the server. You have to configure the client so that it can accept the cert. I think this is currently not directly supported. Instead you have to setup your own OkHttpClient and pass it to the Gentics Mesh Rest Client.

You can use this create method:
```java
MeshRestClient#create(MeshRestClientConfig config, OkHttpClient client)
```
