### ISSUE TITLE
No such index Exception

### ISSUE THREAD

**Issue by philippguertler** [gentics/mesh#143]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.2

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_144

## Problem
Search node endpoint fails and returns http status 400.
Output from mesh log:
```
13:22:30.070 [Sparkling Karrablast] ERROR [elasticsearch[Sparkling Karrablast][listener][T#2]] - Search query failed
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:581) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:113) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.<init>(AbstractSearchAsyncAction.java:99) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.search.SearchDfsQueryThenFetchAsyncAction.<init>(SearchDfsQueryThenFetchAsyncAction.java:57) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:89) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:47) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86) ~[elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56) ~[elasticsearch-2.4.6.jar:2.4.6]
	at com.gentics.mesh.search.SearchRestHandler.handleSearch(SearchRestHandler.java:147) ~[classes/:na]
	at com.gentics.mesh.search.ProjectSearchEndpoint.lambda$registerSearchHandler$3(ProjectSearchEndpoint.java:106) ~[classes/:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[vertx-web-3.4.2.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:85) ~[classes/:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[classes/:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at com.gentics.mesh.etc.RouterStorage.lambda$addProjectRouter$3(RouterStorage.java:317) ~[classes/:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[vertx-web-3.4.2.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.lambda$handleJWTAuth$1(MeshAuthHandler.java:179) ~[classes/:na]
	at com.gentics.mesh.auth.MeshAuthProvider.lambda$authenticateJWT$0(MeshAuthProvider.java:97) ~[classes/:na]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.authenticate(JWTAuthProviderImpl.java:141) ~[vertx-auth-jwt-3.4.2.jar:na]
	at com.gentics.mesh.auth.MeshAuthProvider.authenticateJWT(MeshAuthProvider.java:83) ~[classes/:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handleJWTAuth(MeshAuthHandler.java:164) ~[classes/:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:89) ~[classes/:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[classes/:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:66) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:42) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67) ~[vertx-web-3.4.2.jar:na]
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122) ~[vertx-core-3.4.2.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
13:22:30.070 [Sparkling Karrablast] ERROR [elasticsearch[Sparkling Karrablast][listener][T#2]] - Error for request in path: /api/v1/demo/search/nodes?lang=en,de&page=1&perPage=10
13:22:30.070 [Sparkling Karrablast] ERROR [elasticsearch[Sparkling Karrablast][listener][T#2]] - Error:
com.gentics.mesh.core.rest.error.GenericRestException: 400 Bad Request search_error_query params {}
	at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:85) ~[classes/:na]
	at com.gentics.mesh.search.SearchRestHandler$1.onFailure(SearchRestHandler.java:247) [classes/:na]
	at org.elasticsearch.action.support.ThreadedActionListener$2.doRun(ThreadedActionListener.java:104) [elasticsearch-2.4.6.jar:2.4.6]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-2.4.6.jar:2.4.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
13:22:30.071 [Sparkling Karrablast] WARN  [elasticsearch[Sparkling Karrablast][listener][T#2]] - 127.0.0.1 - - [Mon, 18 Sep 2017 11:22:30 GMT] "POST /api/v1/demo/search/nodes?lang=en,de&page=1&perPage=10 HTTP/1.1" 400 162 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36"
```

## Reproducer
Start a new mesh demo instance. In the Mesh-UI, do the following:
1. Create new Microschema:
```json
{
	"name": "test",
	"fields": [
		{
			"name": "suchmich",
			"label": "",
			"required": false,
			"type": "string",
			"searchIndex": {
				"addRaw": true
			}
		}
	]
}
```
2. Add new field to content schema (micronode, allow previously created microschema)
3. Go back to demo project and try to view the root folder, which will cause some search requests.
4. This will result in the previously mentioned error.

**Comment by Jotschi** [comment]
Bug happens only when there are no nodes for the schema. In those cases no index is being created.

Bug is in NodeMigrationHandler:100
