### ISSUE TITLE
OrientDB Crash due to memory?

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#153]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.1

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_141-b15

## Problem
Not too sure if the Database crashed because it doesn't have enough memory, but it gave out at least some warnings.

Command which has been used to start theServer: `java -jar -Xmx4096m -Dlogback.configurationFile=/opt/mesh-server/logback-local.xml /opt/mesh-server/mesh-server.jar`

Stacktrace:
```
Sep 27, 2017 11:08:21 AM com.orientechnologies.common.log.OLogManager log
WARNING: Received signal: SIGTERM
Sep 27, 2017 11:08:21 AM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
Sep 27, 2017 11:08:21 AM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: storage...
11:18:21,859 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/opt/mesh-server/logback-local.xml] at [file:/opt/mesh-server/logback-local.xml]
11:18:21,955 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:18:21,994 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word meshName with class [com.gentics.mesh.log.MeshLogNameConverter]
11:18:21,994 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:18:22,002 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
11:18:22,045 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:18 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
11:18:22,085 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use gz compression
11:18:22,092 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/mesh.%d{yyyy-MM-dd}.log for the active file
11:18:22,096 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/mesh.%d{yyyy-MM-dd}.log.gz'.
11:18:22,096 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
11:18:22,101 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Sep 27 10:54:07 CEST 2017
11:18:22,102 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:18:22,141 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/mesh.log
11:18:22,141 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/mesh.log]
11:18:22,143 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gentics.mesh] to INFO
11:18:22,143 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
11:18:22,143 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
11:18:22,144 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:18:22,145 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@763d9750 - Registering current configuration as safe fallback point

Sep 27, 2017 11:18:24 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=3,639MB (heap=3,641MB direct=3,641MB os=15,951MB), assuming maximum direct memory size equals to maximum JVM heap size
Sep 27, 2017 11:18:24 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=15951m option when you start the JVM.
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Storage 'storage' was not closed properly. Will try to recover from write ahead log
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Looking for last checkpoint...
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Found FUZZY checkpoint.
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Data restore procedure from FUZZY checkpoint is started.
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=16, position=104512507}} will be skipped during data restore
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} 1 operations were processed, current LSN is LSN{segment=16, position=104512507} last LSN is LSN{segment=16, position=104512560}
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=16, position=104512514}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=16, position=104512467}} will be skipped during data restore
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=16, position=104512554}} will be skipped during data restore
Sep 27, 2017 11:18:29 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Storage data recover was completed
Sep 27, 2017 11:18:33 AM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=storage}} Exception `44A59DA3` in storage `storage`
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/mesh-server/data/graphdb/storage' with mode=rw
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:448)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:311)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:289)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:275)
        at com.gentics.mesh.graphdb.MissingOrientCredentialFixer.fix(MissingOrientCredentialFixer.java:29)
        at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:34)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /opt/mesh-server/data/graphdb/storage
        DB name="storage"
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:687)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
        ... 8 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readLong(DataInputStream.java:416)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:660)
        ... 9 more

Exception in thread "main" com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/mesh-server/data/graphdb/storage' with mode=rw
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:448)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:311)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:289)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:275)
        at com.gentics.mesh.graphdb.MissingOrientCredentialFixer.fix(MissingOrientCredentialFixer.java:29)
        at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:34)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /opt/mesh-server/data/graphdb/storage
        DB name="storage"
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:687)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
        ... 8 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readLong(DataInputStream.java:416)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:660)
        ... 9 more

Exception in thread "main" com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/mesh-server/data/graphdb/storage' with mode=rw
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:448)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:311)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:289)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:275)
        at com.gentics.mesh.graphdb.MissingOrientCredentialFixer.fix(MissingOrientCredentialFixer.java:29)
        at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:34)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /opt/mesh-server/data/graphdb/storage
        DB name="storage"
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:687)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
        ... 8 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readLong(DataInputStream.java:416)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:660)
        ... 9 more
11:21:05,962 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/opt/mesh-server/logback-local.xml] at [file:/opt/mesh-server/logback-local.xml]
11:21:06,024 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:21:06,040 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word meshName with class [com.gentics.mesh.log.MeshLogNameConverter]
11:21:06,041 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:21:06,048 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
11:21:06,085 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:18 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
11:21:06,118 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use gz compression
11:21:06,120 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/mesh.%d{yyyy-MM-dd}.log for the active file
11:21:06,124 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/mesh.%d{yyyy-MM-dd}.log.gz'.
11:21:06,124 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
11:21:06,127 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Sep 27 11:18:22 CEST 2017
11:21:06,129 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:21:06,151 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/mesh.log
11:21:06,151 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/mesh.log]
11:21:06,152 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gentics.mesh] to INFO
11:21:06,153 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
11:21:06,153 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
11:21:06,153 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:21:06,154 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@763d9750 - Registering current configuration as safe fallback point

Sep 27, 2017 11:21:06 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=3,639MB (heap=3,641MB direct=3,641MB os=15,951MB), assuming maximum direct memory size equals to maximum JVM heap size
Sep 27, 2017 11:21:06 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=15951m option when you start the JVM.
Sep 27, 2017 11:22:04 AM com.orientechnologies.common.log.OLogManager log
WARNING: Received signal: SIGTERM
Sep 27, 2017 11:22:04 AM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
Sep 27, 2017 11:22:04 AM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: storage...
Sep 27, 2017 11:22:05 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete
Exception in thread "main" java.lang.IllegalStateException: The current database instance (com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@6b126187) is not active on the current thread (Thread[elasticsearch[Nostalgic Ferrothorn][listener][T#2],5,main]). Current active database is: null
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3391)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1243)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.close(OPartitionedDatabasePool.java:499)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:293)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:448)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:311)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:144)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:85)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:222)
        at com.syncleus.ferma.ext.orientdb.OrientDBTx.<init>(OrientDBTx.java:47)
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:730)
        at com.gentics.mesh.search.index.entry.AbstractIndexHandler.lambda$store$1(AbstractIndexHandler.java:157)
        at rx.Completable$5.call(Completable.java:387)
        at rx.Completable$5.call(Completable.java:381)
        at rx.Completable.unsafeSubscribe(Completable.java:2037)
        at rx.internal.operators.CompletableOnSubscribeMergeIterable.call(CompletableOnSubscribeMergeIterable.java:114)
        at rx.internal.operators.CompletableOnSubscribeMergeIterable.call(CompletableOnSubscribeMergeIterable.java:27)
        at rx.Completable.unsafeSubscribe(Completable.java:2037)
        at rx.Completable$19.call(Completable.java:1368)
        at rx.Completable$19.call(Completable.java:1365)
        at rx.Completable.unsafeSubscribe(Completable.java:2037)
        at rx.Completable.subscribe(Completable.java:2058)
        at rx.internal.operators.CompletableOnSubscribeConcat$CompletableConcatSubscriber.drain(CompletableOnSubscribeConcat.java:129)
        at rx.internal.operators.CompletableOnSubscribeConcat$CompletableConcatSubscriber.innerComplete(CompletableOnSubscribeConcat.java:104)
        at rx.internal.operators.CompletableOnSubscribeConcat$CompletableConcatSubscriber$ConcatInnerSubscriber.onCompleted(CompletableOnSubscribeConcat.java:154)
        at rx.observers.SafeCompletableSubscriber.onCompleted(SafeCompletableSubscriber.java:49)
        at rx.Completable$19$1.onCompleted(Completable.java:1379)
        at rx.internal.operators.CompletableOnSubscribeMergeIterable$1.onCompleted(CompletableOnSubscribeMergeIterable.java:134)
        at rx.Completable$10$1.onCompleted(Completable.java:577)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OperatorDistinct$1.onCompleted(OperatorDistinct.java:78)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:857)
        at rx.internal.producers.SingleProducer.request(SingleProducer.java:75)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onSuccess(SingleLiftObservableOperator.java:76)
        at rx.internal.operators.SingleOnSubscribeDelaySubscriptionOther$1.onSuccess(SingleOnSubscribeDelaySubscriptionOther.java:44)
        at rx.internal.util.ScalarSynchronousSingle$1.call(ScalarSynchronousSingle.java:36)
        at rx.internal.util.ScalarSynchronousSingle$1.call(ScalarSynchronousSingle.java:32)
        at rx.Single.subscribe(Single.java:1876)
        at rx.internal.operators.SingleOnSubscribeDelaySubscriptionOther$2.onCompleted(SingleOnSubscribeDelaySubscriptionOther.java:81)
        at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
        at rx.Completable$30.onCompleted(Completable.java:2088)
        at com.gentics.mesh.search.impl.ElasticSearchProvider$7.onResponse(ElasticSearchProvider.java:398)
        at com.gentics.mesh.search.impl.ElasticSearchProvider$7.onResponse(ElasticSearchProvider.java:391)
        at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:89)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NullPointerException
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:309)
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1086)
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1079)
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1072)
                at com.tinkerpop.blueprints.util.wrappers.wrapped.WrappedGraph.shutdown(WrappedGraph.java:30)
                at com.syncleus.ferma.ext.orientdb.OrientDBTx.close(OrientDBTx.java:65)
                at com.gentics.mesh.cli.BootstrapInitializerImpl.lambda$new$0(BootstrapInitializerImpl.java:153)
                at com.gentics.mesh.cli.BootstrapInitializerImpl.reindexAll(BootstrapInitializerImpl.java:409)
                at com.gentics.mesh.cli.BootstrapInitializerImpl.handleLocalData(BootstrapInitializerImpl.java:380)
                at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:278)
                at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:106)
                at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:84)
                at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:51)
11:22:22,193 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/opt/mesh-server/logback-local.xml] at [file:/opt/mesh-server/logback-local.xml]
11:22:22,256 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:22:22,271 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word meshName with class [com.gentics.mesh.log.MeshLogNameConverter]
11:22:22,272 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:22:22,279 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
11:22:22,316 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:18 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
11:22:22,349 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use gz compression
11:22:22,351 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/mesh.%d{yyyy-MM-dd}.log for the active file
11:22:22,354 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/mesh.%d{yyyy-MM-dd}.log.gz'.
11:22:22,354 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
11:22:22,358 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Sep 27 11:22:06 CEST 2017
11:22:22,359 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:22:22,382 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/mesh.log
11:22:22,382 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/mesh.log]
11:22:22,384 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gentics.mesh] to INFO
11:22:22,384 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
11:22:22,384 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
11:22:22,385 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:22:22,385 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@763d9750 - Registering current configuration as safe fallback point

Sep 27, 2017 11:22:23 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=3,639MB (heap=3,641MB direct=3,641MB os=15,951MB), assuming maximum direct memory size equals to maximum JVM heap size
Sep 27, 2017 11:22:23 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=15951m option when you start the JVM.
```
This made the entire server unavailable (Neither from the API nor from the UI) and had to be focefully stopped and restarted. After that it deleted quite a lot of nodes, but I think I found a pattern.

I think it may be that the deleted nodes are the ones I created earlier that day or after a reboot. Since I'm not sure on how Mesh is saving the content permanently, it may be that it still saved the changes in cache rather than to do it permanently. And since OrientDB crashed it just dropped those.
This is just speculation tho.

If you need further information than let me know

**Comment by Jotschi** [comment]
1. Is the listed log output before or after the crash? The first thing I see is the "WARNING: Received signal: SIGTERM" - This means the server process has been shutdown via the SIGTERM signal.
2. Why do you think nodes have been deleted. Do you have uuids of those nodes? Can those nodes still be loaded via the REST API or are those nodes just not listed in the search index?
3. Is the server setup correctly?  https://getmesh.io/docs/beta/administration-guide.html#_system_requirements
4. Do you have an exact timestamp of the crash?
5. Do you know what actions were executed before the crash?

**Comment by SiNEXiST** [comment]
1. This is the log during the crash. There's stuff before that but it shouldn't be relevant as it was too far back. And yes, just as I said in the first post

> This made the entire server unavailable (Neither from the API nor from the UI) and had to be focefully stopped and restarted. 

2. After further inspection it seems that the UI is having some issues somewhere. There're no errors in the console, but it seems like it's an issue with the user-handling. The missing nodes are created from another user. When I load the nodes however, I got all permissions as I'm logged in as admin. I'll look further into it and report on what the issue might be.

3. The files `/etc/security/limits.conf` and `/etc/pam.d/su` haven't been edited yet, so not at the time of the crash no. Made the changes now tho

4. Sadly not, but it had to happen between 30mins or so since that was the last time I checked it and it was working.

5. Nothing special. Creating and publishing some nodes (Max 10)

**Comment by SiNEXiST** [comment]
Okay, tested some more on that and the elements are simply not in the search-index. It's possible to load them as children or directly via the UUID. When I publish/edit them, they are in the search-index again. So no loss of nodes luckily.

**Comment by Jotschi** [comment]
I see the following error in the logs:
> Caused by: java.nio.file.AccessDeniedException: /opt/mesh-server/data/searchindex

Were the permissions correct? Was the index placed on NFS?

> java.lang.OutOfMemoryError: Direct buffer memory

I would increase the direct memory buffer and heap as suggested:
> MAXHEAP=-Xmx2875M 2) MAXDISKCACHE=4404
