### ISSUE TITLE
Remove unresolvable completed Jobs

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#179]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## JVM
- Open JDK 1.8.0_131

## Problem
Completed Jobs which can't be resolved properly cause the mesh job-list to crash:
```
09:18:22.376 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-4] [OrientDBDatabase.java:798] - Error handling transaction
java.lang.NullPointerException: null
        at com.gentics.mesh.core.data.job.impl.JobImpl.transformToRestSync(JobImpl.java:89) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobImpl.transformToRestSync(JobImpl.java:41) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.TransformableElement.transformToRest(TransformableElement.java:38) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.page.TransformablePage.transformToRest(TransformablePage.java:33) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.admin.JobHandler.lambda$handleReadList$0(JobHandler.java:68) ~[mesh-server.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operateTx$12(HandlerUtilities.java:243) [mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operate$16(HandlerUtilities.java:277) [mesh-server.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[mesh-server.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
09:18:22.377 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-6] [FailureHandler.java:91] - Error for request in path: /api/v1/admin/jobs?null
09:18:22.379 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-6] [FailureHandler.java:93] - Error:
java.lang.NullPointerException: null
        at com.gentics.mesh.core.data.job.impl.JobImpl.transformToRestSync(JobImpl.java:89) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobImpl.transformToRestSync(JobImpl.java:41) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.TransformableElement.transformToRest(TransformableElement.java:38) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.page.TransformablePage.transformToRest(TransformablePage.java:33) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.admin.JobHandler.lambda$handleReadList$0(JobHandler.java:68) ~[mesh-server.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operateTx$12(HandlerUtilities.java:243) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operate$16(HandlerUtilities.java:277) ~[mesh-server.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[mesh-server.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

## Reproduction
- Create a Schema
- Update that Schema to cause a migration
- Delete the Schema after the migration is finished
- Attempt to open `/admin/jobs` which results in the error posted above

## Expected behaviour and actual behaviour
When there's an uncompletable task such as described in the Problem, it should silently be removed. Another way would be to simply remove all jobs of the Schema when the Schema gets deleted.

Currently you have to either remove it manually b accessing the Database or resetting it.

**Comment by Jotschi** [comment]
TODO: No migration and no job should be scheduled if the schema version is not referencing any containers.

**Comment by philippguertler** [comment]
Null checks for referenced elements have been added when loading jobs via REST with version [0.25.0](https://getmesh.io/docs/changelog/#v0.25.0). This should not happen anymore.
