### ISSUE TITLE
Multiple schema/microschema creation or update causes timeouts

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#190]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Linux
- MacOSX
- Windows

## JVM
- Open JDK 1.8.0_151

## Problem

Creating or updating a lot of schemas and microschemas in a short timespan (We use this when we import all of our data),
it happens that there's an Database issue that causes a timeout on the request.

```
10:24:54.428 [Nostalgic Ferrothorn] INFO  [vert.x-eventloop-thread-0] [LoggerHandlerImpl.java:156] - 127.0.0.1 - - [Thu, 09 Nov 2017 09:24:54 GMT] "POST /api/v1/kofl/microschemas/70d0e8319fba4c4690e8319fba5c4632 HTTP/1.1" 200 1523 "-" "-"
10:24:54.433 [Nostalgic Ferrothorn] INFO  [vert.x-eventloop-thread-4] [LoggerHandlerImpl.java:156] - 127.0.0.1 - - [Thu, 09 Nov 2017 09:24:54 GMT] "POST /api/v1/kofl/microschemas/e7626cad277940dea26cad277920de30 HTTP/1.1" 200 7373 "-" "-"
10:25:34.455 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-9] [Database.java:84] - Timeout while processing result of transaction handler.
java.util.concurrent.TimeoutException: Timed out after 40000ms waiting for underlying Observable.
	at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:110) ~[mesh-server.jar:na]
	at com.gentics.mesh.graphdb.spi.Database.lambda$null$0(Database.java:81) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[mesh-server.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
10:25:34.455 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [Database.java:84] - Timeout while processing result of transaction handler.
java.util.concurrent.TimeoutException: Timed out after 40000ms waiting for underlying Observable.
	at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:110) ~[mesh-server.jar:na]
	at com.gentics.mesh.graphdb.spi.Database.lambda$null$0(Database.java:81) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[mesh-server.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
10:25:34.464 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-9] [Database.java:85] - Calling transaction stacktrace.
java.lang.Exception: Transaction timeout exception
	at com.gentics.mesh.graphdb.spi.Database.operateTx(Database.java:68) ~[mesh-server.jar:na]
	at com.gentics.mesh.core.verticle.microschema.MicroschemaCrudHandler.handleAddMicroschemaToProject(MicroschemaCrudHandler.java:178) ~[mesh-server.jar:na]
	at com.gentics.mesh.core.verticle.microschema.ProjectMicroschemaEndpoint.lambda$addAssignHandler$1(ProjectMicroschemaEndpoint.java:76) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:85) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at com.gentics.mesh.etc.RouterStorage.lambda$addProjectRouter$3(RouterStorage.java:317) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.lambda$handleJWTAuth$1(MeshAuthHandler.java:179) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthProvider.lambda$authenticateJWT$0(MeshAuthProvider.java:97) ~[mesh-server.jar:na]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.authenticate(JWTAuthProviderImpl.java:141) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthProvider.authenticateJWT(MeshAuthProvider.java:83) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handleJWTAuth(MeshAuthHandler.java:164) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:89) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:66) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:42) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71) ~[mesh-server.jar:na]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[mesh-server.jar:na]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[mesh-server.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:49) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:27) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[mesh-server.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[mesh-server.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[mesh-server.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
10:25:34.466 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [Database.java:85] - Calling transaction stacktrace.
java.lang.Exception: Transaction timeout exception
	at com.gentics.mesh.graphdb.spi.Database.operateTx(Database.java:68) ~[mesh-server.jar:na]
	at com.gentics.mesh.core.verticle.microschema.MicroschemaCrudHandler.handleAddMicroschemaToProject(MicroschemaCrudHandler.java:178) ~[mesh-server.jar:na]
	at com.gentics.mesh.core.verticle.microschema.ProjectMicroschemaEndpoint.lambda$addAssignHandler$1(ProjectMicroschemaEndpoint.java:76) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:85) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at com.gentics.mesh.etc.RouterStorage.lambda$addProjectRouter$3(RouterStorage.java:317) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:255) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorise(AuthHandlerImpl.java:86) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.lambda$handleJWTAuth$1(MeshAuthHandler.java:179) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthProvider.lambda$authenticateJWT$0(MeshAuthProvider.java:97) ~[mesh-server.jar:na]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.authenticate(JWTAuthProviderImpl.java:141) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthProvider.authenticateJWT(MeshAuthProvider.java:83) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handleJWTAuth(MeshAuthHandler.java:164) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:89) ~[mesh-server.jar:na]
	at com.gentics.mesh.auth.MeshAuthHandler.handle(MeshAuthHandler.java:34) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:66) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:42) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78) ~[mesh-server.jar:na]
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180) ~[mesh-server.jar:na]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[mesh-server.jar:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71) ~[mesh-server.jar:na]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[mesh-server.jar:na]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[mesh-server.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:49) ~[mesh-server.jar:na]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:27) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[mesh-server.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[mesh-server.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[mesh-server.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[mesh-server.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
```

**Comment by Jotschi** [comment]
How much is `a lot`?

**Comment by SiNEXiST** [comment]
We currently import 20 microschemas and 19 schemas

**Comment by Jotschi** [comment]
We have refactored the tx handling and removed the sync operation on ES. I don't think this issue is still relevant. I have also added a test which creates schemas in-parallel.
