### ISSUE TITLE
Locked Schema updates

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#191]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Linux
- MacOSX
- Windows

## JVM
- Open JDK 1.8.0_151

## Problem

This Problem is a bit tricky as it doesn't happen consistently (At least I couldn't find a way to re-produce it).
Anyways, the Issue is that when you attempt to update an schema when nodes exist with that schema, it'll sometimes
bring up this error.

The more annoying part is, that this "locks" the schema. It can not be updated anymore, unless you delete all
existing nodes with this schema. If you do it after everything is deleted, it works fine again.

Errors I get when I attempt to update these:
```
09:38:49.908 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-4] [OrientDBDatabase.java:798] - Error handling transaction
com.gentics.mesh.core.rest.error.GenericRestException: 500 Internal Server Error error_index_unknown params {node-10c0fbbc4a7b49ce80fbbc4a7bd9ce72-fbdd48e5cb3d4d7f9d48e5cb3d0d7f47-e5737651087f4182b37651087f31829f-draft}
        at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:85) ~[mesh-server.jar:na]
        at com.gentics.mesh.search.index.node.NodeIndexHandler.createIndex(NodeIndexHandler.java:343) ~[mesh-server.jar:na]
        at com.gentics.mesh.search.index.common.CreateIndexEntryImpl.process(CreateIndexEntryImpl.java:64) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.search.impl.SearchQueueBatchImpl.lambda$null$5(SearchQueueBatchImpl.java:238) ~[mesh-server.jar:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
        at com.gentics.mesh.core.data.search.impl.SearchQueueBatchImpl.lambda$processAsync$11(SearchQueueBatchImpl.java:238) ~[mesh-server.jar:na]
        at rx.Completable$5.call(Completable.java:387) ~[mesh-server.jar:na]
        at rx.Completable$5.call(Completable.java:381) ~[mesh-server.jar:na]
        at rx.Completable.unsafeSubscribe(Completable.java:2037) ~[mesh-server.jar:na]
        at rx.Completable.await(Completable.java:1088) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.search.impl.SearchQueueBatchImpl.processSync(SearchQueueBatchImpl.java:274) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.search.impl.SearchQueueBatchImpl.processSync(SearchQueueBatchImpl.java:282) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.NodeMigrationJobImpl.prepare(NodeMigrationJobImpl.java:50) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.enqueueSchemaMigration(JobRootImpl.java:106) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.impl.ReleaseImpl.assignSchemaVersion(ReleaseImpl.java:258) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.schema.SchemaCrudHandler.lambda$null$0(SchemaCrudHandler.java:154) [mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$1(TxFactory.java:71) [mesh-server.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:70) [mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.schema.SchemaCrudHandler.lambda$handleUpdate$1(SchemaCrudHandler.java:99) [mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$1(TxFactory.java:71) [mesh-server.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:70) [mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operateTx$14(HandlerUtilities.java:256) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$operate$16(HandlerUtilities.java:277) ~[mesh-server.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[mesh-server.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

## Reproducer

Sadly couldn't make any out

## Expected behaviour and actual behaviour

Expected the content to either update or stop preventing me to update the schema once it's errored.

**Comment by Jotschi** [comment]
@philippguertler I assume you fixed this issue recently. Can you take a look at the exception?

**Comment by Jotschi** [comment]
ES operations are now decoupled from REST calls. Thus this error can no longer happen.
