### ISSUE TITLE
Thread has been blocked

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#205]
## Gentics Mesh Version, operating system, or hardware.
- v0.10.4

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_141

## Problem

Not sure what happened, but some kind of OutOfMememory did which caused the database to shutdown and inaccessible for mesh.
Here are the logs. Most of them were spammed in the log quite long before getting to the next error (All in chronicle order).

```
14:53:18.052 [Nostalgic Ferrothorn] INFO  [elasticsearch[Nostalgic Ferrothorn][listener][T#2]] [SearchQueueBatchImpl.java:251] - Search queue entry batch completed {1/1}
14:53:52.068 [Nostalgic Ferrothorn] ERROR [elasticsearch[Nostalgic Ferrothorn][listener][T#2]] [ElasticSearchProvider.java:415] - Adding object {6fc272dfa53440e68272dfa53480e66d-de:node} to index failed. Duration 27031[ms]
org.elasticsearch.index.engine.IndexFailedEngineException: Index failed for [node#6fc272dfa53440e68272dfa53480e66d-de]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:459) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:605) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378) ~[mesh-server-0.10.4.jar:na]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
14:53:52.068 [Nostalgic Ferrothorn] ERROR [elasticsearch[Nostalgic Ferrothorn][listener][T#2]] [SearchQueueBatchImpl.java:263] - Error while processing batch {null}
```

```
14:54:01.774 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [JobWorkerVerticle.java:93] - Error while processing jobs
com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:306) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:620) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:75) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.util.wrappers.wrapped.WrappedGraph.getVertex(WrappedGraph.java:38) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:177) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:30) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.traversals.SimpleTraversal.<init>(SimpleTraversal.java:56) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.AbstractVertexFrame.out(AbstractVertexFrame.java:93) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.root.RootVertex.findAllDynamic(RootVertex.java:68) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.findAllIt(JobRootImpl.java:94) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.process(JobRootImpl.java:205) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$null$3(JobWorkerVerticle.java:89) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$0(TxFactory.java:58) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$2(TxFactory.java:83) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:82) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:57) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$processJobs$4(JobWorkerVerticle.java:87) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$executeLocked$6(JobWorkerVerticle.java:129) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
        Suppressed: com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:306) ~[mesh-server-0.10.4.jar:na]
                at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.rollback(OrientTransactionalGraph.java:191) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.ext.orientdb.DelegatingFramedOrientGraph.rollback(DelegatingFramedOrientGraph.java:75) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.tx.AbstractTx.rollback(AbstractTx.java:91) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.ext.orientdb.OrientDBTx.close(OrientDBTx.java:58) ~[mesh-server-0.10.4.jar:na]
                at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:776) ~[mesh-server-0.10.4.jar:na]
                ... 10 common frames omitted
14:54:01.774 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [JobWorkerVerticle.java:124] - Error while acquiring global migration lock {mesh.internal.joblock}
io.vertx.core.VertxException: Timed out waiting to get lock
        at io.vertx.core.shareddata.impl.AsynchronousLock$LockWaiter.lambda$timedOut$1(AsynchronousLock.java:100) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

```
14:54:02.052 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [JobWorkerVerticle.java:93] - Error while processing jobs
io.vertx.core.VertxException: Timed out waiting to get lock
        at io.vertx.core.shareddata.impl.AsynchronousLock$LockWaiter.lambda$timedOut$1(AsynchronousLock.java:100) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
14:54:02.052 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [JobWorkerVerticle.java:124] - Error while acquiring global migration lock {mesh.internal.joblock}
io.vertx.core.VertxException: Timed out waiting to get lock
        at io.vertx.core.shareddata.impl.AsynchronousLock$LockWaiter.lambda$timedOut$1(AsynchronousLock.java:100) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

```
14:54:02.720 [Nostalgic Ferrothorn] ERROR [vert.x-worker-thread-8] [OrientDBDatabase.java:798] - Error handling transaction
com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:306) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:620) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:75) ~[mesh-server-0.10.4.jar:na]
        at com.tinkerpop.blueprints.util.wrappers.wrapped.WrappedGraph.getVertex(WrappedGraph.java:38) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:177) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:30) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.traversals.SimpleTraversal.<init>(SimpleTraversal.java:56) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.AbstractVertexFrame.out(AbstractVertexFrame.java:93) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.root.RootVertex.findAllDynamic(RootVertex.java:68) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.findAllIt(JobRootImpl.java:94) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.process(JobRootImpl.java:205) ~[mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$null$3(JobWorkerVerticle.java:89) [mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$0(TxFactory.java:58) [mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$2(TxFactory.java:83) [mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:773) ~[mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:82) [mesh-server-0.10.4.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:57) [mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$processJobs$4(JobWorkerVerticle.java:87) [mesh-server-0.10.4.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$executeLocked$6(JobWorkerVerticle.java:129) [mesh-server-0.10.4.jar:na]
        at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.10.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
        Suppressed: com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
                at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:306) ~[mesh-server-0.10.4.jar:na]
                at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.rollback(OrientTransactionalGraph.java:191) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.ext.orientdb.DelegatingFramedOrientGraph.rollback(DelegatingFramedOrientGraph.java:75) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.tx.AbstractTx.rollback(AbstractTx.java:91) ~[mesh-server-0.10.4.jar:na]
                at com.syncleus.ferma.ext.orientdb.OrientDBTx.close(OrientDBTx.java:58) ~[mesh-server-0.10.4.jar:na]
                at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:776) ~[mesh-server-0.10.4.jar:na]
                ... 10 common frames omitted
```

```
00:14:03.141 [Nostalgic Ferrothorn] WARN  [vertx-blocked-thread-checker] [BlockedThreadChecker.java:57] - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 26065083 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
        at io.vertx.ext.web.impl.RouteImpl.matches(RouteImpl.java:229) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:70) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:148) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$$Lambda$269/1968763737.handle(Unknown Source) ~[na:na]
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.VertxHttpHandler$$Lambda$271/271405859.run(Unknown Source) ~[na:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.impl.ContextImpl$$Lambda$50/1086491405.run(Unknown Source) ~[na:na]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server-0.10.4.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[mesh-server-0.10.4.jar:na]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server-0.10.4.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[mesh-server-0.10.4.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:49) ~[mesh-server-0.10.4.jar:na]
        at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:27) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[mesh-server-0.10.4.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[mesh-server-0.10.4.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[mesh-server-0.10.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

**Comment by Jotschi** [comment]
> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

@SiNEXiST Please add your memory settings to the issue

**Comment by SiNEXiST** [comment]
@Jotschi We started the server with the default maximal-heapsize which is ~2GB (or 2051014656 bytes to be exact).

**Comment by Jotschi** [comment]
The issue was that elasticsearch encountered an OOM and tried to shut down the server. This issue will be resolved once we add support for remote ES 6.x - See #169 #43
