### ISSUE TITLE
Error while creating Image

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#236]
## Gentics Mesh Version, operating system, or hardware.
- v0.11.5

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_151

## Problem
As I was trying to make a reproducer for another Issue, I noticed that I can't create an Image (Custom Node). Throws the following Error:

```
13:44:33.645 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-0] [FailureHandler.java:98] - Error for request in path: /api/v1/kofl/nodes/274f4b250cd74c5a8f4b250cd7bc5a43/binary/content?lang=de
13:44:33.645 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-0] [FailureHandler.java:100] - Error:
org.elasticsearch.index.mapper.StrictDynamicMappingException: mapping set to strict, dynamic introduction of [sha512sum] within [fields.content] is not allowed
        at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:605) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:444) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:264) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:308) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:328) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:254) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:308) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:328) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:254) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:124) ~[mesh-server.jar:na]
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309) ~[mesh-server.jar:na]
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:584) ~[mesh-server.jar:na]
        at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:563) ~[mesh-server.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211) ~[mesh-server.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223) ~[mesh-server.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157) ~[mesh-server.jar:na]
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66) ~[mesh-server.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657) ~[mesh-server.jar:na]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[mesh-server.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287) ~[mesh-server.jar:na]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279) ~[mesh-server.jar:na]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77) ~[mesh-server.jar:na]
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378) ~[mesh-server.jar:na]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[mesh-server.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
13:44:33.647 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-0] [LoggerHandlerImpl.java:152] - 127.0.0.1 - - [Fri, 15 Dec 2017 12:44:33 GMT] "POST /api/v1/kofl/nodes/274f4b250cd74c5a8f4b250cd7bc5a43/binary/content?lang=de HTTP/1.1" 500 117 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
```

Response:
```json
{
  "message" : "mapping set to strict, dynamic introduction of [sha512sum] within [fields.content] is not allowed"
}
```

Schema
```json
{
	"name": "custom_image",
	"displayField": "name",
	"container": false,
	"binary": false,
	"fields": [
		{
			"name": "content",
			"label": "",
			"required": false,
			"type": "binary"
		},
		{
			"name": "name",
			"label": "Name",
			"required": false,
			"type": "string",
			"elasticsearch": {
				"raw": {
					"index": "not_analyzed",
					"type": "string"
				}
			}
		}
	]
}
```

**Comment by Jotschi** [comment]
Please manually invoke a reindex. That will fix the issue. I'll include a fix in the next release which avoid this problem for older installations. (Not yours)
