### ISSUE TITLE
Clustering startup failure - java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#257]
**Error:** Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelFutureListener

```
14:32:13.561 [] INFO  [main] - Configuration file {mesh.yml} was not found within classpath.
14:32:13.589 [] INFO  [main] - Configuration file {config/mesh.yml} was not found within filesystem.
14:32:13.781 [] INFO  [main] - Saved default configuration to file {/media/nvm/mesh/mesh/server/config/mesh.yml}.
14:32:13.781 [] INFO  [main] - Loading default configuration.
14:32:13.785 [Heavenly Rhydon] INFO  [main] - Could not find keystore {config/keystore.jceks}. Creating one for you..
14:32:13.879 [Heavenly Rhydon] INFO  [main] - Keystore {config/keystore.jceks} created. The keystore password is listed in your {mesh.yml} file.
14:32:13.879 [Heavenly Rhydon] INFO  [main] - ###############################################################
14:32:13.880 [Heavenly Rhydon] INFO  [main] - # Mesh Version 0.14.1-SNAPSHOT 2018-01-16T19:57:50Z           #
14:32:13.880 [Heavenly Rhydon] INFO  [main] - # Gentics Software                                            #
14:32:13.880 [Heavenly Rhydon] INFO  [main] - #-------------------------------------------------------------#
14:32:13.883 [Heavenly Rhydon] INFO  [main] - # Vert.x Version: 3.5.0                                       #
14:32:13.883 [Heavenly Rhydon] INFO  [main] - # Cluster Name: test                                          #
14:32:13.883 [Heavenly Rhydon] INFO  [main] - # Mesh Node Name: Heavenly Rhydon                             #
14:32:13.883 [Heavenly Rhydon] INFO  [main] - ###############################################################
14:32:13.941 [Heavenly Rhydon] INFO  [main] - Creating orientdb distributed server configuration file {config/default-distributed-db-config.json}
14:32:13.941 [Heavenly Rhydon] INFO  [main] - Creating orientdb hazelcast configuration file {config/hazelcast.xml}
14:32:13.941 [Heavenly Rhydon] INFO  [main] - Creating orientdb server configuration file {config/orientdb-server-config.xml}
14:32:13.941 [Heavenly Rhydon] INFO  [main] - Creating orientdb server security configuration file {config/security.json}
14:32:14.052 [Heavenly Rhydon] INFO  [main] - No networkHost setting was specified within the cluster settings. Using the determined IP {192.168.10.200}.
14:32:14.165 [Heavenly Rhydon] INFO  [main] - [Heavenly Rhydon] version[2.4.6], pid[23128], build[5376dca/2017-07-18T12:17:44Z]
14:32:14.166 [Heavenly Rhydon] INFO  [main] - [Heavenly Rhydon] initializing ...
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelFutureListener
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at org.elasticsearch.common.inject.internal.FailableCache.get(FailableCache.java:51)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:51)
	at org.elasticsearch.common.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:50)
	at org.elasticsearch.common.inject.InjectorImpl.initializeBinding(InjectorImpl.java:405)
	at org.elasticsearch.common.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:680)
	at org.elasticsearch.common.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:615)
	at org.elasticsearch.common.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:183)
	at org.elasticsearch.common.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:139)
	at org.elasticsearch.common.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:686)
	at org.elasticsearch.common.inject.FactoryProxy.notify(FactoryProxy.java:45)
	at org.elasticsearch.common.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:243)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at com.gentics.mesh.search.impl.MeshNode.<init>(MeshNode.java:14)
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:166)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:242)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:115)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:81)
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:53)
Caused by: java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelFutureListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at org.elasticsearch.common.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:190)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:60)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
	at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at org.elasticsearch.common.inject.internal.FailableCache$1.load(FailableCache.java:39)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.ChannelFutureListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
14:32:14.713 [Heavenly Rhydon] INFO  [Thread-0] - Mesh shutting down...
14:32:14.717 [Heavenly Rhydon] ERROR [Thread-0] - Error while shutting down mesh.
java.lang.NullPointerException: null
	at com.gentics.mesh.graphdb.OrientDBDatabase.stop(OrientDBDatabase.java:125) ~[classes/:na]
	at com.gentics.mesh.cli.MeshImpl.shutdown(MeshImpl.java:312) ~[classes/:na]
	at com.gentics.mesh.cli.MeshImpl$1.run(MeshImpl.java:230) ~[classes/:na]
```

**Comment by Jotschi** [comment]
The issue is not fixable without downgrading vert.x to 3.4.x thus we have no other option but to proceed and remove the embedded ES from Mesh. #169
