### ISSUE TITLE
Migration for Schemas which didn't change

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#271]
## Gentics Mesh Version, operating system, or hardware.
- v0.13.1

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_151

## Problem

I updated a schema (added a field) which caused unrelated schemas which I haven't touched to undergo an Migration.

To that, apparently the migration doesn't seem to go well with Vertx, as I get quite some Error messages that the Thread is blocked in different variations:

```
14:31:28.215 [Nostalgic Ferrothorn] WARN  [vertx-blocked-thread-checker] [BlockedThreadChecker.java:57] - Thread Thread[vert.x-worker-thread-1,5,main] has been blocked for 146434 ms, time limit is 60000
io.vertx.core.VertxException: Thread blocked
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:85) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.filter.CollectionFilterPipe.processNextStart(CollectionFilterPipe.java:35) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.filter.BackFilterPipe.processNextStart(BackFilterPipe.java:33) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.transform.OrderPipe.processNextStart(OrderPipe.java:92) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98) ~[mesh-server.jar:na]
        at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105) ~[mesh-server.jar:na]
        at com.syncleus.ferma.traversals.AbstractVertexTraversal.nextOrDefaultExplicit(AbstractVertexTraversal.java:425) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.impl.ReleaseImpl.findLatestMicroschemaVersion(ReleaseImpl.java:244) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.root.impl.MicroschemaContainerRootImpl.fromReference(MicroschemaContainerRootImpl.java:127) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.node.field.impl.MicronodeGraphFieldImpl.lambda$static$1(MicronodeGraphFieldImpl.java:86) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.node.field.impl.MicronodeGraphFieldImpl$$Lambda$20/51705243.update(Unknown Source) ~[na:na]
        at com.gentics.mesh.core.data.impl.GraphFieldTypes.updateField(GraphFieldTypes.java:168) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.container.impl.AbstractGraphFieldContainerImpl.updateField(AbstractGraphFieldContainerImpl.java:333) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.container.impl.AbstractGraphFieldContainerImpl.updateFieldsFromRest(AbstractGraphFieldContainerImpl.java:348) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.container.impl.NodeGraphFieldContainerImpl.updateFieldsFromRest(NodeGraphFieldContainerImpl.java:210) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.AbstractMigrationHandler.migrate(AbstractMigrationHandler.java:139) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.node.NodeMigrationHandler.migrateDraftContainer(NodeMigrationHandler.java:246) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.node.NodeMigrationHandler.lambda$migrateContainer$0(NodeMigrationHandler.java:177) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.node.NodeMigrationHandler$$Lambda$595/897620206.handle(Unknown Source) ~[na:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:832) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.node.NodeMigrationHandler.migrateContainer(NodeMigrationHandler.java:153) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.migration.node.NodeMigrationHandler.migrateNodes(NodeMigrationHandler.java:101) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.NodeMigrationJobImpl.processTask(NodeMigrationJobImpl.java:93) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobImpl.process(JobImpl.java:284) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.data.job.impl.JobRootImpl.process(JobRootImpl.java:215) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$null$3(JobWorkerVerticle.java:89) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle$$Lambda$590/1067255322.handle(Unknown Source) ~[na:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$0(TxFactory.java:58) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory$$Lambda$591/329089763.handle(Unknown Source) ~[na:na]
        at com.syncleus.ferma.tx.TxFactory.lambda$tx$2(TxFactory.java:83) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory$$Lambda$592/2126012311.handle(Unknown Source) ~[na:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:832) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:82) ~[mesh-server.jar:na]
        at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:57) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$processJobs$4(JobWorkerVerticle.java:87) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle$$Lambda$585/791993975.run(Unknown Source) ~[na:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle.lambda$executeLocked$6(JobWorkerVerticle.java:129) ~[mesh-server.jar:na]
        at com.gentics.mesh.core.verticle.job.JobWorkerVerticle$$Lambda$587/1600638773.handle(Unknown Source) ~[na:na]
        at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66) ~[mesh-server.jar:na]
        at io.vertx.core.shareddata.impl.AsynchronousLock$$Lambda$589/1849861697.handle(Unknown Source) ~[na:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) ~[mesh-server.jar:na]
        at io.vertx.core.impl.ContextImpl$$Lambda$57/407285007.run(Unknown Source) ~[na:na]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80) ~[mesh-server.jar:na]
        at io.vertx.core.impl.TaskQueue$$Lambda$47/1354725727.run(Unknown Source) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
## Expected behaviour and actual behaviour

To not trigger an Migration for Schemas which haven't changed

**Comment by Jotschi** [comment]
@SiNEXiST  Please write a reproducer or test for this issue

**Comment by Jotschi** [comment]
Affected Blocking code has been reworked/ removed. Migration issue can't be addressed without more information.
