### ISSUE TITLE
Running mvn test on "Image via imgscalr" service fails on the `testResize` method of `ImgscalrImageManipulatorTest`

### ISSUE THREAD

**Issue by onerandomgig** [gentics/mesh#275]
## Gentics Mesh Version, operating system, or hardware.
- v0.15.x

## Operating System
- Any

## JVM
- Open JDK 1.8.0_100

## Problem
There seems to be an issue when I run the mvn "test" goal for the "Image via imgscalr" service. Specifically i get the error - "400 Bad Request image_error_writing_failed".

The root cause seems to be this line in the "Common" project
`String[] parts = sha512sum.split("(?<=\\G.{8})");` inside the `getCacheFile` method of `AbstractImageManipulator`

The error seems to arise because it cannot find the file - data/binaryImageCache/**blank.gi/f/**image-rw150rh180.jpg

It looks like the regex expression is invalid.

## Reproducer
Execute the mvn goal "test" on the "Image via imgscalr" service. The `testResize` method of `ImgscalrImageManipulatorTest` fails.

## Expected behaviour and actual behaviour
All tests should run successfully.

**Comment by Jotschi** [comment]
The test is just passing just fine locally as well as on our Jenkins Server. Can you please share which OS you are using and the full exception of the test error?

**Comment by Jotschi** [comment]
@onerandomgig Which branch are you using? Which head revision?

**Comment by onerandomgig** [comment]
@Jotschi This is the surefire report

-------------------------------------------------------------------------------
Test set: com.gentics.mesh.image.ImgscalrImageManipulatorTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.627 s <<< FAILURE! - in com.gentics.mesh.image.ImgscalrImageManipulatorTest
testResize(com.gentics.mesh.image.ImgscalrImageManipulatorTest)  Time elapsed: 10.283 s  <<< FAILURE!
java.lang.AssertionError: Timeout reached
	at org.junit.Assert.fail(Assert.java:88)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.lambda$testResize$1(ImgscalrImageManipulatorTest.java:82)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.checkImages(ImgscalrImageManipulatorTest.java:127)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.testResize(ImgscalrImageManipulatorTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)

I am running this on a Mac
I am on the master branch. This is the head revision - c75993eebb9e65161db2b726d6297ddf28027d8d

**Comment by onerandomgig** [comment]
Here is a complete stack trace

`java.io.FileNotFoundException: data/binaryImageCache/blume2.jpe/g/image-rw150rh180.jpg (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
	at javax.imageio.ImageIO.write(ImageIO.java:1530)
	at com.gentics.mesh.image.ImgscalrImageManipulator.lambda$null$0(ImgscalrImageManipulator.java:204)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:110)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:107)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
io.reactivex.exceptions.OnErrorNotImplementedException: 400 Bad Request image_error_writing_failed
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.vertx.reactivex.core.WorkerExecutor$4.handle(WorkerExecutor.java:157)
	at io.vertx.reactivex.core.WorkerExecutor$4.handle(WorkerExecutor.java:152)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:102)
	at io.vertx.reactivex.core.Future.fail(Future.java:207)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:79)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:110)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:107)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 400 Bad Request image_error_writing_failed
	at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:111)
	at com.gentics.mesh.image.ImgscalrImageManipulator.lambda$null$0(ImgscalrImageManipulator.java:206)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
	... 11 more
Caused by: java.lang.NullPointerException
	at javax.imageio.ImageIO.write(ImageIO.java:1538)
	at com.gentics.mesh.image.ImgscalrImageManipulator.lambda$null$0(ImgscalrImageManipulator.java:204)
	... 12 more
Exception in thread "vert.x-eventloop-thread-2" io.reactivex.exceptions.OnErrorNotImplementedException: 400 Bad Request image_error_writing_failed
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.vertx.reactivex.core.WorkerExecutor$4.handle(WorkerExecutor.java:157)
	at io.vertx.reactivex.core.WorkerExecutor$4.handle(WorkerExecutor.java:152)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:102)
	at io.vertx.reactivex.core.Future.fail(Future.java:207)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:79)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:110)
	at io.vertx.reactivex.core.WorkerExecutor$2.handle(WorkerExecutor.java:107)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 400 Bad Request image_error_writing_failed
	at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:111)
	at com.gentics.mesh.image.ImgscalrImageManipulator.lambda$null$0(ImgscalrImageManipulator.java:206)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
	... 11 more
Caused by: java.lang.NullPointerException
	at javax.imageio.ImageIO.write(ImageIO.java:1538)
	at com.gentics.mesh.image.ImgscalrImageManipulator.lambda$null$0(ImgscalrImageManipulator.java:204)
	... 12 more
[INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.972 s - in com.gentics.mesh.image.focalpoint.FocalPointModifierImageTest
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.726 s <<< FAILURE! - in com.gentics.mesh.image.ImgscalrImageManipulatorTest
[ERROR] testResize(com.gentics.mesh.image.ImgscalrImageManipulatorTest)  Time elapsed: 10.294 s  <<< FAILURE!
java.lang.AssertionError: Timeout reached
	at org.junit.Assert.fail(Assert.java:88)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.lambda$testResize$1(ImgscalrImageManipulatorTest.java:82)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.checkImages(ImgscalrImageManipulatorTest.java:127)
	at com.gentics.mesh.image.ImgscalrImageManipulatorTest.testResize(ImgscalrImageManipulatorTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)`

**Comment by Jotschi** [comment]
@onerandomgig Thanks for the stacktrace. I can't explain the issue you are seeing but I'll check whether I can figure out why this is happening on your system. So far I have only seen issues with some systems generating slightly different output images which triggered the pixel by pixel assert.

Can you perhaps share your workspace path? Does it include special characters? Normally the regex should split up the UUID of the image in multiple segments but in your case it seems to utilize the filename.

**Comment by onerandomgig** [comment]
Thanks @Jotschi. This is my workspace path - `/Users/Prashanth/SourceControl/OpenSource/GenticsMesh`

All the sub projects are under this folder. I run the "install" goal on the root pom. Even running the "test" goal on the imgscalr service pom results in the same error.

**Comment by Jotschi** [comment]
Hi @onerandomgig, I was able to reproduce the test issue. I think it is a test execution related problem. Still need to do more debugging.

**Comment by Jotschi** [comment]
@onerandomgig The test issue is now fixed. Thanks for reporting it.
