### ISSUE TITLE
Fix NPE in permission store

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#286]
This exception happens when clustering is enabled.

```
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: java.lang.NullPointerException: null
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at com.gentics.mesh.core.cache.PermissionStore.invalidate(PermissionStore.java:75) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at com.gentics.mesh.core.cache.PermissionStore.invalidate(PermissionStore.java:83) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at com.gentics.mesh.distributed.DistributedEventManager.handleClusterTopologyUpdate(DistributedEventManager.java:104) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at com.gentics.mesh.distributed.DistributedEventManager.lambda$registerHandlers$1(DistributedEventManager.java:60) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212) [mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:189) [mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:538) [mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[mesh-server-0.16.0.jar:na]
Feb 13 13:51:03 gtxwstwdev01.apa.at java[24394]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

**Comment by Jotschi** [comment]
Happend only during init. Null check was added some time ago. Closing the issue.
