### ISSUE TITLE
Deleting a Node causes issues on other requests

### ISSUE THREAD

**Issue by SiNEXiST** [gentics/mesh#287]
## Gentics Mesh Version, operating system, or hardware.
- v0.14.2

## Problem

There's an issue regarding the deletion of a node while an other process/request is running. For example, when you perform a search an load X nodes. While the search is still performing and you happen to delete a node which is found by the search, the delete-request will go through, while the search-request will raise an error `"No vertex for Id {#197:147467} could be found within the graph`.

The same thing happens when you attempt to load a container-node and you delete nodes inside of it. I assume it's because it can't build the childrenInfo and therefore fails.

Exception:
```
14:52:17.980 [Nostalgic Ferrothorn] ERROR [vert.x-eventloop-thread-3] [FailureHandler.java:100] - Error:
java.lang.RuntimeException: No vertex for Id {#197:147467} could be found within the graph
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:194) ~[mesh-server-0.14.2.jar:na]
        at com.gentics.mesh.core.data.generic.MeshVertexImpl.getElement(MeshVertexImpl.java:34) ~[mesh-server-0.14.2.jar:na]
        at com.syncleus.ferma.traversals.SimpleTraversal.<init>(SimpleTraversal.java:56) ~[mesh-server-0.14.2.jar:na]
        at com.syncleus.ferma.AbstractVertexFrame.out(AbstractVertexFrame.java:93) ~[mesh-server-0.14.2.jar:na]
        at com.gentics.mesh.core.data.node.impl.NodeImpl.getSchemaContainer(NodeImpl.java:462) ~[mesh-server-0.14.2.jar:na]
        at com.gentics.mesh.core.data.node.impl.NodeImpl.transformToRestSync(NodeImpl.java:558) ~[mesh-server-0.14.2.jar:na]
        at com.gentics.mesh.core.data.node.impl.NodeImpl.lambda$transformToRest$25(NodeImpl.java:1984) ~[mesh-server-0.14.2.jar:na]
        at com.gentics.mesh.graphdb.spi.Database.lambda$null$3(Database.java:120) ~[mesh-server-0.14.2.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:278) ~[mesh-server-0.14.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

## Reproducer

This one doesn't always happen, but it's better to reproduce it with a bigger amount of nodes (30k+) and a small amount of memory as it slows down mesh and makes it easier to hit the timing-window.
- Start a search-request for a bigger group of Nodes
- Start a delete-request for a node that would fit into the search-result while the search-request is still ongoing

**Comment by Jotschi** [comment]
This will no longer happen on 0.15.0 since the way how search results are processed has been changed. The search result will now only process the nodes which are within the resulting page. Previously all nodes had to be processed in order to apply the permission and language filters.
