### ISSUE TITLE
Question about workerPoolSize best value 

### ISSUE THREAD

**Issue by cschockaert** [gentics/mesh#464]
## Gentics Mesh Version, operating system, or hardware.
- v0.21.4

## Operating System
- MacOSX

## JVM
docker getmesh + embedded es

## Problem
did some tuning in getmesh,
using default config + modified vertx option workerPoolSize from 20 to 40

I got some failed request + this debug log:
when i ab test a graphql request:

```
ab                \
-n 2000         \
-c 40         \
-s 10             \
-p post_data  \
-g ab_out \
-T 'application/json'   \
-v 1            \
-H 'Accept: application/json' \
-C 'mesh.token=xxxx'   \
http://localhost:8080/api/v1/test/graphql/
```

```
mesh-node1_1  | [2018-07-11T11:57:02,996][DEBUG][o.e.a.s.TransportSearchAction] [nQ4W-_m] [403012] Failed to execute query phase
mesh-node1_1  | org.elasticsearch.transport.RemoteTransportException: [nQ4W-_m][127.0.0.1:9300][indices:data/read/search[phase/query/id]]
mesh-node1_1  | Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.common.util.concurrent.TimedRunnable@7de73eb3 on QueueResizingEsThreadPoolExecutor[search, queue capacity = 1000, min queue capacity = 1000, max queue capacity = 1000, frame size = 2000, targeted response rate = 1s, task execution EWMA = 303.7micros, adjustment amount = 50, QueueResizingEsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor@61a5cad0[Running, pool size = 13, active threads = 13, queued tasks = 1000, completed tasks = 848293]]]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:48) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_111-internal]
mesh-node1_1  | 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_111-internal]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.doExecute(EsThreadPoolExecutor.java:94) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.doExecute(QueueResizingEsThreadPoolExecutor.java:93) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:89) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:648) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.access$000(TransportService.java:74) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:135) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:594) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:514) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:554) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:545) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchTransportService.sendExecuteQuery(SearchTransportService.java:162) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.DfsQueryPhase.run(DfsQueryPhase.java:79) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:146) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:140) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase.successfulShardExecution(InitialSearchPhase.java:251) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase.onShardResult(InitialSearchPhase.java:239) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase.access$200(InitialSearchPhase.java:49) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$innerOnResponse$0(InitialSearchPhase.java:212) ~[elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:212) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:522) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1049) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1118) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1108) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1097) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchTransportService$5$1.onResponse(SearchTransportService.java:352) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.action.search.SearchTransportService$5$1.onResponse(SearchTransportService.java:348) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.search.SearchService$1.onResponse(SearchService.java:261) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.search.SearchService$1.onResponse(SearchService.java:257) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.2.jar:6.1.2]
mesh-node1_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111-internal]
mesh-node1_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111-internal]
mesh-node1_1  | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]`
```

## 4 worker thread

```
Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /api/v1/test/graphql/
Document Length:        582 bytes

Concurrency Level:      40
Time taken for tests:   36.962 seconds
Complete requests:      2000
Failed requests:        0
Total transferred:      1938000 bytes
Total body sent:        3132000
HTML transferred:       1164000 bytes
Requests per second:    54.11 [#/sec] (mean)
Time per request:       739.246 [ms] (mean)
Time per request:       18.481 [ms] (mean, across all concurrent requests)
Transfer rate:          51.20 [Kbytes/sec] received
                        82.75 kb/s sent
                        133.95 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   5.2      0     104
Processing:    54  729 149.9    704    1482
Waiting:       54  728 149.6    703    1481
Total:         56  729 149.7    704    1483

Percentage of the requests served within a certain time (ms)
  50%    704
  66%    738
  75%    764
  80%    789
  90%    886
  95%   1018
  98%   1237
  99%   1299
 100%   1483 (longest request)
```

## 20 worker thread

```
Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /api/v1/test/graphql/
Document Length:        582 bytes

Concurrency Level:      40
Time taken for tests:   25.262 seconds
Complete requests:      2000
Failed requests:        0
Total transferred:      1938000 bytes
Total body sent:        3132000
HTML transferred:       1164000 bytes
Requests per second:    79.17 [#/sec] (mean)
Time per request:       505.238 [ms] (mean)
Time per request:       12.631 [ms] (mean, across all concurrent requests)
Transfer rate:          74.92 [Kbytes/sec] received
                        121.08 kb/s sent
                        195.99 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       4
Processing:    93  500  82.2    497     869
Waiting:       93  499  81.5    496     869
Total:         95  500  82.2    497     869

Percentage of the requests served within a certain time (ms)
  50%    497
  66%    526
  75%    543
  80%    558
  90%    597
  95%    635
  98%    696
  99%    732
 100%    869 (longest request)
```

## 40 worker thread

```
Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /api/v1/test/graphql/
Document Length:        582 bytes

Concurrency Level:      40
Time taken for tests:   32.933 seconds
Complete requests:      2000
Failed requests:        8
   (Connect: 0, Receive: 0, Length: 8, Exceptions: 0)
Total transferred:      1934420 bytes
Total body sent:        3132000
HTML transferred:       1160424 bytes
Requests per second:    60.73 [#/sec] (mean)
Time per request:       658.661 [ms] (mean)
Time per request:       16.467 [ms] (mean, across all concurrent requests)
Transfer rate:          57.36 [Kbytes/sec] received
                        92.87 kb/s sent
                        150.23 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       4
Processing:    79  656 181.3    597    1405
Waiting:       79  655 181.0    596    1401
Total:         80  656 181.3    598    1406

Percentage of the requests served within a certain time (ms)
  50%    598
  66%    665
  75%    725
  80%    778
  90%    945
  95%   1045
  98%   1155
  99%   1236
 100%   1406 (longest request)
```

## Expected behaviour and actual behaviour

no exception

note that in default setting 20 worker thread it's working fine.

is that normal that with more worker thread in getmesh, elasticsearch is not working fine?

**Comment by Jotschi** [comment]
@cschockaert Interesting results. Last week I ran similar tests and did not encounter the issue. Can you share your query so that we can judge the complexity? Normally Elasticsearch has a request queue of 1000. If the requests exceed the queue you will get query errors because ES can't process the queries. It it however very interesting that the queue capacity is actually being pushed to the limit. I would expect the queue size to never exceed the __worker size * verticle count (5)__.



> mesh-node1_1  | Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.common.util.concurrent.TimedRunnable@7de73eb3 on QueueResizingEsThreadPoolExecutor[search, __queue capacity = 1000__, min queue capacity = 1000, max queue capacity = 1000, frame size = 2000, targeted response rate = 1s, task execution EWMA = 303.7micros, adjustment amount = 50, QueueResizingEsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor@61a5cad0[Running, pool size = 13, active threads = 13, queued tasks = 1000, completed tasks = 848293]]]

**Comment by Jotschi** [comment]
@cschockaert Can you reproduce the issue with an external ES? I just tried the a very basic query on a huge dataset (1M nodes) and workersize of 40. I was not able to reproduce the issue using an external ES. If you do performance tests (especially when involving an ES) I recommend to use a dedicated ES. We plan to make the ES optional in the future and only include the embedded ES in our demo.

```
Server Software:        
Server Hostname:        a.b.c.d
Server Port:            8080

Document Path:          /api/v1/test/graphql
Document Length:        65 bytes

Concurrency Level:      40
Time taken for tests:   7.741 seconds
Complete requests:      2000
Failed requests:        0
Total transferred:      352000 bytes
Total body sent:        1072000
HTML transferred:       130000 bytes
Requests per second:    258.35 [#/sec] (mean)
Time per request:       154.826 [ms] (mean)
Time per request:       3.871 [ms] (mean, across all concurrent requests)
Transfer rate:          44.40 [Kbytes/sec] received
                        135.23 kb/s sent
                        179.64 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.6      1       9
Processing:    52  153  44.6    146     445
Waiting:       52  153  44.6    146     445
Total:         56  154  44.8    147     448

Percentage of the requests served within a certain time (ms)
  50%    147
  66%    162
  75%    173
  80%    179
  90%    198
  95%    219
  98%    269
  99%    353
 100%    448 (longest request)
```

**Comment by Jotschi** [comment]
@cschockaert Are you okay with closing this issue? I think we made a lot of improvements in the past. 0.32.0 for example completely removes the blocking code from Create,Update,Delete requests.

**Comment by cschockaert** [comment]
Yes thanks
