### ISSUE TITLE
Unable to delete microschema, after it had been updated

### ISSUE THREAD

**Issue by npomaroli** [gentics/mesh#589]
## Gentics Mesh Version, operating system, or hardware.
- v0.28.2

## Problem

After a microschema has been updated, it can no longer be deleted.

## Reproducer

1. Create microschema
2. Update microschema by adding an additional field
3. Try to delete the microschema

## Expected behaviour and actual behaviour

Expected: microschema should be deleted
Actual: Request gets a 500 response.

Logged exception:
```
org.apache.commons.lang.NotImplementedException: The deletion behaviour for this vertex was not implemented.
    at com.gentics.mesh.core.data.generic.MeshVertexImpl.delete(MeshVertexImpl.java:166) ~[mesh.jar:na]
    at com.gentics.mesh.core.data.container.impl.MicroschemaContainerVersionImpl.delete(MicroschemaContainerVersionImpl.java:168) ~[mesh.jar:na]
    at com.gentics.mesh.core.data.container.impl.MicroschemaContainerImpl.delete(MicroschemaContainerImpl.java:61) ~[mesh.jar:na]
    at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$null$0(HandlerUtilities.java:98) ~[mesh.jar:na]
    at com.syncleus.ferma.tx.TxFactory.lambda$tx$1(TxFactory.java:71) ~[mesh.jar:na]
    at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:931) ~[mesh.jar:na]
    at com.syncleus.ferma.tx.TxFactory.tx(TxFactory.java:70) ~[mesh.jar:na]
    at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$deleteElement$1(HandlerUtilities.java:94) ~[mesh.jar:na]
    at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:931) ~[mesh.jar:na]
    at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$asyncTx$12(HandlerUtilities.java:260) ~[mesh.jar:na]
    at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$async$17(HandlerUtilities.java:304) ~[mesh.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[mesh.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
10:49:29.136 [Comical Zangoose] ERROR [vert.x-eventloop-thread-0] - Unexpected exception in route
java.lang.IllegalArgumentException: code: -1 (expected: 0+)
    at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:581) ~[mesh.jar:na]
    at io.netty.handler.codec.http.HttpResponseStatus.<init>(HttpResponseStatus.java:569) ~[mesh.jar:na]
    at io.netty.handler.codec.http.HttpResponseStatus.valueOf(HttpResponseStatus.java:446) ~[mesh.jar:na]
    at io.vertx.core.http.impl.HttpServerResponseImpl.setStatusCode(HttpServerResponseImpl.java:112) ~[mesh.jar:na]
    at com.gentics.mesh.router.route.FailureHandler.handle(FailureHandler.java:147) ~[mesh.jar:na]
    at com.gentics.mesh.router.route.FailureHandler.handle(FailureHandler.java:27) ~[mesh.jar:na]
    at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:235) ~[mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117) ~[mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133) [mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:465) [mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:166) [mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextWrapper.fail(RoutingContextWrapper.java:73) [mesh.jar:na]
    at io.vertx.ext.web.impl.RoutingContextWrapper.fail(RoutingContextWrapper.java:73) [mesh.jar:na]
    at com.gentics.mesh.context.impl.InternalRoutingActionContextImpl.fail(InternalRoutingActionContextImpl.java:131) [mesh.jar:na]
    at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$async$18(HandlerUtilities.java:310) [mesh.jar:na]
    at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79) ~[mesh.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289) ~[mesh.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[mesh.jar:na]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[mesh.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[mesh.jar:na]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[mesh.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[mesh.jar:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```

**Comment by Jotschi** [comment]
TODO:

* Add test
* Check https://github.com/gentics/mesh/pull/762
