### ISSUE TITLE
CMS can't start because of Waiting the status of Elasticsearch

### ISSUE THREAD

**Issue by suihanhbr** [gentics/mesh#625]
## Gentics Mesh Version, operating system, or hardware.
- v0.29.1

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_100

## Problem
The CMS system can't start normally.

```
ERROR [main] - Error while starting mesh
java.lang.RuntimeException: Elasticsearch was not ready within set timeout of {45} seconds.
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:158) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
22:25:42.723 [Graceful Palkia] INFO  [main] - Mesh shutting down...
22:25:42.797 [Graceful Palkia] INFO  [main] - Closing Elasticsearch REST client.
22:25:42.797 [Graceful Palkia] INFO  [main] - Stopping Elasticsearch server.
22:25:43.797 [] INFO  [main] - Shutdown completed...
22:25:43.799 [] INFO  [Thread-0] - Mesh shutting down...
22:25:43.799 [] INFO  [Thread-0] - Closing Elasticsearch REST client.
22:25:43.799 [] INFO  [Thread-0] - Stopping Elasticsearch server.
22:25:43.799 [] INFO  [Thread-0] - Shutdown completed...
```

**Comment by Jotschi** [comment]
It seems that ES could not be started. Did you get any earlier errors? We are currently working on making Elasticsearch optional. This way there will be no delay and wait check during the startup of Mesh.

**Comment by suihanhbr** [comment]
here is all of the output
```
java -jar mesh-server-0.29.1.jar 
22:24:55.407 [] INFO  [main] - Configuration file {mesh.yml} was not found within classpath.
22:24:55.474 [] INFO  [main] - Loading configuration file {config/mesh.yml}.
22:24:55.749 [Graceful Palkia] INFO  [main] - ###############################################################
22:24:55.750 [Graceful Palkia] INFO  [main] - # Mesh Version 0.29.1 2019-01-16T11:40:17Z                    #
22:24:55.750 [Graceful Palkia] INFO  [main] - # Gentics Software                                            #
22:24:55.750 [Graceful Palkia] INFO  [main] - #-------------------------------------------------------------#
22:24:55.754 [Graceful Palkia] INFO  [main] - # Vert.x Version: 3.5.4                                       #
22:24:55.754 [Graceful Palkia] INFO  [main] - # Mesh Node Name: Graceful Palkia                             #
22:24:55.754 [Graceful Palkia] INFO  [main] - ###############################################################
22:24:56.202 [Graceful Palkia] INFO  [main] - Creating non-clustered Vert.x instance
22:24:56.460 [Graceful Palkia] INFO  [main] - Running with native transports enabled
22:24:56.665 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:24:57.667 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:24:58.668 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:24:59.669 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:00.670 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:01.672 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:02.673 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:03.674 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:04.675 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:05.676 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:06.677 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:07.679 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:08.680 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:09.681 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:10.682 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:11.683 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:12.685 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:13.686 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:14.687 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:15.689 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:16.690 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:17.691 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:18.692 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:19.693 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:20.694 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:21.696 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:22.697 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:23.698 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:24.699 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:25.700 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:26.702 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:27.703 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:28.704 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:29.705 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:30.707 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:31.708 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:32.709 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:33.710 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:34.711 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:35.712 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:36.714 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:37.715 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:38.716 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:39.717 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:40.718 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:41.719 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
22:25:42.723 [Graceful Palkia] ERROR [main] - Error while starting mesh
java.lang.RuntimeException: Elasticsearch was not ready within set timeout of {45} seconds.
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:158) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
22:25:42.723 [Graceful Palkia] INFO  [main] - Mesh shutting down...
22:25:42.797 [Graceful Palkia] INFO  [main] - Closing Elasticsearch REST client.
22:25:42.797 [Graceful Palkia] INFO  [main] - Stopping Elasticsearch server.
22:25:43.797 [] INFO  [main] - Shutdown completed...
22:25:43.799 [] INFO  [Thread-0] - Mesh shutting down...
22:25:43.799 [] INFO  [Thread-0] - Closing Elasticsearch REST client.
22:25:43.799 [] INFO  [Thread-0] - Stopping Elasticsearch server.
22:25:43.799 [] INFO  [Thread-0] - Shutdown completed...
```

**Comment by Jotschi** [comment]
@suihanhbr Please post your `mesh.yml` file and add 

```
	<logger name="com.gentics.mesh.search" level="DEBUG"/>
```

to your `logback.xml` configuration file. This will enable verbose debug output.

**Comment by suihanhbr** [comment]
here is the content of mesh.yml
```
---
defaultMaxDepth: 10
defaultLanguage: "en"
updateCheck: true
vertxOptions:
  workerPoolSize: 20
  eventPoolSize: 4
tempDirectory: "data/tmp"
pluginDirectory: "plugins"
nodeName: "Graceful Palkia"
httpServer:
  port: 9393
  host: "0.0.0.0"
  corsAllowedOriginPattern: ""
  corsAllowCredentials: false
  enableCors: false
 ssl: false
  certPath: "config/cert.pem"
  keyPath: "config/key.pem"
cluster:
  enabled: false
  vertxPort: 0
storage:
  directory: "data/graphdb"
  backupDirectory: "data/backup"
  exportDirectory: "data/export"
  startServer: false
  parameters: {}
search:
  url: "http://localhost:9200"
  timeout: 8000
  startupTimeout: 45
  startEmbedded: false
  embeddedArgument
   \ -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0\
    \ -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -XX:+HeapDumpOnOutOfMemoryError"
  bulkLimit: 2000
  prefix: "mesh-"
upload:
  byteLimit: 262144000
  directory: "data/binaryFiles"
  tempDirectory: "data/tmp/file-uploads"
security:
  tokenExpirationTime: 3600
  keystorePassword: "8d4e3c3db574438b8e3c3db574c38bb9"
  keystorePath: "config/keystore.jceks"
  algorithm: "HS256"
  enableAnonymousAccess: true
  oauth2:
    enabled: false
    mapperScriptDevMode: false
image:
  imageCacheDirectory: "data/binaryImageCache"
  maxWidth: 2048
  maxHeight: 2048
```

**Comment by suihanhbr** [comment]
here is the ouput 
```
16:54:16.161 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
16:54:17.162 [Graceful Palkia] DEBUG [main] - Checking elasticsearch status...
16:54:17.163 [Graceful Palkia] DEBUG [main] - Error while checking elasticsearch status.
com.gentics.elasticsearch.client.HttpErrorException: Error while excuting request
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.executeSync(ElasticsearchOkClient.java:109) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.RequestBuilder.sync(RequestBuilder.java:81) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:138) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9200
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.lambda$createClient$0(ElasticsearchOkClient.java:55) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.executeSync(ElasticsearchOkClient.java:93) ~[mesh-server-0.29.1.jar:na]
	... 8 common frames omitted
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_191]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246) ~[mesh-server-0.29.1.jar:na]
	... 29 common frames omitted
16:54:17.163 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
16:54:18.163 [Graceful Palkia] DEBUG [main] - Timeout of {45} reached.
16:54:18.164 [Graceful Palkia] ERROR [main] - Error while starting mesh
java.lang.RuntimeException: Elasticsearch was not ready within set timeout of {45} seconds.
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:158) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
16:54:18.164 [Graceful Palkia] INFO  [main] - Mesh shutting down...
16:54:18.237 [Graceful Palkia] INFO  [main] - Closing Elasticsearch REST client.
16:54:18.237 [Graceful Palkia] INFO  [main] - Stopping Elasticsearch server.
16:54:19.237 [] INFO  [main] - Shutdown completed...
16:54:19.239 [] INFO  [Thread-0] - Mesh shutting down...
16:54:19.239 [] INFO  [Thread-0] - Closing Elasticsearch REST client.
16:54:19.239 [] INFO  [Thread-0] - Stopping Elasticsearch server.
16:54:19.239 [] INFO  [Thread-0] - Shutdown completed...
```

**Comment by Jotschi** [comment]
@suihanhbr  You set `search.startEmbedded` to false. Thus no embedded ES will be started. Instead Gentics Mesh tries to connect to `http://localhost:9200`. It expects that you started your dedicated ES which can be reached using that address. This does not work and thus the startup fails.

**Comment by suihanhbr** [comment]
I set `search.startEmbedded` to false because it don't work.
I try it again with 'search.startEmbedded' = true. But it still don't work.
```
19:40:51.884 [] INFO  [main] - Configuration file {mesh.yml} was not found within classpath.
19:40:51.950 [] INFO  [main] - Loading configuration file {config/mesh.yml}.
19:40:52.266 [Graceful Palkia] INFO  [main] - ###############################################################
19:40:52.267 [Graceful Palkia] INFO  [main] - # Mesh Version 0.29.1 2019-01-16T11:40:17Z                    #
19:40:52.267 [Graceful Palkia] INFO  [main] - # Gentics Software                                            #
19:40:52.267 [Graceful Palkia] INFO  [main] - #-------------------------------------------------------------#
19:40:52.270 [Graceful Palkia] INFO  [main] - # Vert.x Version: 3.5.4                                       #
19:40:52.270 [Graceful Palkia] INFO  [main] - # Mesh Node Name: Graceful Palkia                             #
19:40:52.271 [Graceful Palkia] INFO  [main] - ###############################################################
19:40:52.737 [Graceful Palkia] INFO  [main] - Creating non-clustered Vert.x instance
19:40:52.998 [Graceful Palkia] INFO  [main] - Running with native transports enabled
19:40:52.999 [Graceful Palkia] DEBUG [main] - Creating elasticsearch provider.
19:40:53.012 [Graceful Palkia] INFO  [main] - Starting watchdog for Elasticsearch process
19:40:53.330 [Graceful Palkia] DEBUG [main] - Checking elasticsearch status...
.......
19:41:37.459 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
19:41:38.459 [Graceful Palkia] DEBUG [main] - Checking elasticsearch status...
19:41:38.461 [Graceful Palkia] DEBUG [main] - Error while checking elasticsearch status.
com.gentics.elasticsearch.client.HttpErrorException: Error while excuting request
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.executeSync(ElasticsearchOkClient.java:109) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.RequestBuilder.sync(RequestBuilder.java:81) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:138) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9200
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.lambda$createClient$0(ElasticsearchOkClient.java:55) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient.executeSync(ElasticsearchOkClient.java:93) ~[mesh-server-0.29.1.jar:na]
	... 8 common frames omitted
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_191]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) ~[mesh-server-0.29.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246) ~[mesh-server-0.29.1.jar:na]
	... 29 common frames omitted
19:41:38.461 [Graceful Palkia] INFO  [main] - Waiting for elasticsearch status...
19:41:39.461 [Graceful Palkia] DEBUG [main] - Timeout of {45} reached.
19:41:39.462 [Graceful Palkia] ERROR [main] - Error while starting mesh
java.lang.RuntimeException: Elasticsearch was not ready within set timeout of {45} seconds.
	at com.gentics.mesh.search.impl.ElasticSearchProvider.waitForCluster(ElasticSearchProvider.java:158) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:116) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.search.impl.ElasticSearchProvider.start(ElasticSearchProvider.java:79) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:298) ~[mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.1.jar:na]
	at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.1.jar:na]
19:41:39.462 [Graceful Palkia] INFO  [main] - Mesh shutting down...
19:41:39.528 [Graceful Palkia] INFO  [main] - Closing Elasticsearch REST client.
19:41:39.528 [Graceful Palkia] INFO  [main] - Stopping Elasticsearch server.
19:41:40.529 [Graceful Palkia] INFO  [main] - Terminating Elasticsearch process..
19:41:41.529 [] INFO  [main] - Shutdown completed...
19:41:41.531 [] INFO  [Thread-0] - Mesh shutting down...
19:41:41.531 [] INFO  [Thread-0] - Closing Elasticsearch REST client.
19:41:41.531 [] INFO  [Thread-0] - Stopping Elasticsearch server.
19:41:41.531 [] INFO  [Thread-0] - Shutdown completed...
```

**Comment by suihanhbr** [comment]
I had tested the  version 0.29.3, it still don't work with the same output .

**Comment by suihanhbr** [comment]
I had found out the reason for this issue. Elasticsearch can't run under the root privilege. I change to a normal account and run mesh , it do work.

**Comment by Jotschi** [comment]
@suihanhbr Good catch. I did not think of that situation.

**Comment by Jotschi** [comment]
We are currently completely reworking the ES integration in #522 - Closing this issue
