### ISSUE TITLE
Client can't login with rest-client

### ISSUE THREAD

**Issue by suihanhbr** [gentics/mesh#652]
## Gentics Mesh Version, operating system, or hardware.
- v0.29.3
- connect to "demo.getmesh.io" is the same

## Operating System
- Linux(Server)
- MacOSX(host)

## JVM
- Open JDK 1.8.0_191

## Problem

I try this code like that:
```
		client = MeshRestClient.create("demo.getmesh.io", 443, true, vertx);
		client.setLogin("admin", "admin");
		client.login().blockingGet();
```

It did not success and blocks thread always.

```
二月 20, 2019 6:54:39 下午 io.vertx.core.impl.BlockedThreadChecker
警告: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2791 ms, time limit is 2000
二月 20, 2019 6:54:40 下午 io.vertx.core.impl.BlockedThreadChecker
警告: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3794 ms, time limit is 2000
二月 20, 2019 6:54:41 下午 io.vertx.core.impl.BlockedThreadChecker
警告: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4796 ms, time limit is 2000
二月 20, 2019 6:54:42 下午 io.vertx.core.impl.BlockedThreadChecker
警告: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5801 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:83)
	at io.reactivex.Single.blockingGet(Single.java:2154)
	at com.suihan.cms.MainVerticle.start(MainVerticle.java:58)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$10(DeploymentManager.java:481)
	at io.vertx.core.impl.DeploymentManager$$Lambda$8/143110009.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.vertx.core.impl.ContextImpl$$Lambda$9/1132547352.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

any advice for that?

**Comment by Jotschi** [comment]
@suihanhbr You are using the "old" Mesh REST client within Vert.x. By calling blockingGet you will block the eventloop execution of the Verticle. I suggest you update to Mesh version `0.30.1` which already contains a different implementation of the Mesh Rest Client which uses OkHttp. I recommend you use the async style and invoke subscribe on the single which you get from the `login()` method.
