### ISSUE TITLE
Dead lock situation when doing CRUD actions in cluster mode and new mesh instance starting up

### ISSUE THREAD

**Issue by cschockaert** [gentics/mesh#994]
## Gentics Mesh Version, operating system, or hardware.
- v1.3.2

## Operating System
- Linux

## Problem
```
13:30:45.465 [i.v.c.i.BlockedThreadChecker] WARN  [vertx-blocked-thread-checker] - Thread Thread[vert.x-worker-thread-0,5,main]=Thread[vert.x-worker-thread-0,5,main] has been blocked for 320183708 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.Semaphore.acquire(Unknown Source)
	at app//com.gentics.mesh.core.verticle.handler.HandlerUtilities.lock(HandlerUtilities.java:353)
	at app//com.gentics.mesh.core.endpoint.node.NodeCrudHandler.handleDelete(NodeCrudHandler.java:77)
	at app//com.gentics.mesh.core.endpoint.node.NodeEndpoint.lambda$addDeleteHandler$15(NodeEndpoint.java:405)
	at app//com.gentics.mesh.core.endpoint.node.NodeEndpoint$$Lambda$747/0x0000000100c58c40.handle(Unknown Source)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1368/0x0000000100ded440.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$366/0x0000000100926440.run(Unknown Source)
	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at app//io.vertx.core.impl.TaskQueue$$Lambda$362/0x0000000100927c40.run(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.3/java.lang.Thread.run(Unknown Source)
```

New instance node cannot startup, mesh instance does not go into BACKUP mode and dont stream his db to the new mesh instance joining node

## Reproducer
use MESH_GRAPH_SYNC_WRITES = true (default value in mesh.yml)

Start 1 mesh instance in cluster mode, on the background make a lot of CRUD updates over mesh data.
Start a second mesh instance node. 1st instance is going in BACKUP node,

some actions like deleting will fail:

```
com.gentics.mesh.core.endpoint.node.NodeCrudHandler#handleDelete

@Override
	public void handleDelete(InternalActionContext ac, String uuid) {
		validateParameter(uuid, "uuid");

		utils.lock();
		utils.syncTx(ac, () -> {
			try {
				Node node = getRootVertex(ac).loadObjectByUuid(ac, uuid, DELETE_PERM);
				if (node.getProject().getBaseNode().getUuid().equals(node.getUuid())) {
					throw error(METHOD_NOT_ALLOWED, "node_basenode_not_deletable");
				}
				// Create the batch first since we can't delete the container and access it later in batch creation
				utils.bulkableAction(bac -> {
					node.deleteFromBranch(ac, ac.getBranch(), bac, false);
				});
			} finally {
				utils.unlock();
			}
		}, () -> ac.send(NO_CONTENT));
	}
```
utils.lock will occur but utils.unlock will not

## Expected behaviour and actual behaviour

unlock should always be called even if something is wrong.

**Comment by Jotschi** [comment]
Relates to private issue - https://www.prjhub.com/#/issues/10884

**Comment by Jotschi** [comment]
As mentioned in gitter. We need to analyze a heap dump of the locked instance in order to determine which elements caused the deadlock. Once we determined which elements caused this we may be able to write a reproducer or add a workaround.

**Comment by Jotschi** [comment]
Initial work on reproducer can be found here: 
https://github.com/Jotschi/orientdb-cluster-test/tree/issue-10884

**Comment by Jotschi** [comment]
Internal notes:

Locked Rids:
* -1,447
* -1, 804
* -1, 700
* -1, 448

Locked Keys:
* See `ONewDistributedTxContextImpl` lists.

**Comment by Jotschi** [comment]
We addressed deadlocks by implementing cluster topology locks. Please update and enable the topologyLocks. Those should fix the error.
